### ISSUE TITLE
Issue does not show on release notes after it was reopened then closed

### ISSUE THREAD

**Issue by ipolevoy** [github-tools/github-release-notes#223]
Here is the  chain of events:

1. Generated release notes: https://github.com/javalite/javalite/releases/tag/javalite-2.3.1-j8 with commmand: 

`gren release -t javalite-2.3.1-j8 activejdbc-root-2.3 --override`

The issue https://github.com/javalite/javalite/issues/913 is on the release notes.

2. Reopened https://github.com/javalite/javalite/issues/913 to not forget to document a new feature. 

3. Regenerate release notes with the same command. The issue is now gone from release notes. 
4. Closed the issue  and regenerated release notes again, but the issue is no longer on the list. 

My config file: 
```
---
  dataSource: "issues"
  prefix: ""
  ignoreIssuesWith: 
    - "In-Progress"
    - "Priority-High"
    - "Priority-Low"
    - "Priority-Medium"
    - "Rejected"
    - "Type-Review"
    - "bug"
    - "duplicate"
    - "enhancement"
    - "imported"
    - "question"
  onlyMilestones: false
  groupBy: false
#      ActiveJDBC:
#        - "Module: ActiveJDBC"
#      ActiveWeb:
#          - "Module: ActiveWeb"

  changelogFilename: "CHANGELOG.md"

```

Is there a flag I can use to bring the reopened then closed issues  back or this is a bug?
