### ISSUE TITLE
How to remove [label] prefix in the groupBy'd issue release generation?

### ISSUE THREAD

**Issue by xetra11** [github-tools/github-release-notes#290]
I am having the following `gren.yml` configuration file:
```yml
  dataSource: "issues"
  prefix: "v"
  includeMessages: "commits"
  changelogFilename: "CHANGELOG.md"
  ignoreCommitsWith: ["chore", "github"]
  ignoreIssuesWith: "continues deployment"
  groupBy:
    Enhancements: ["enhancement", "feature"]
    Bug Fixes: ["bug"]
```

It does group the labels properly but also prefix's the issue title in the changelog with the label:

---
#### Enhancements

- [**enhancement**] test feature number 2 [#12](https://github.com/xetra11/CK3-Workbench/issues/12)

#### Bug Fixes

- [**bug**] test bug number 2 [#13](https://github.com/xetra11/CK3-Workbench/issues/13)

---

I want to get rid of the `[**enhancement**]` and `[**bug**]` prefix here. Any idea how to do so?

The custom template mentioned here: https://github-tools.github.io/github-release-notes/options.html#configuration-file seems only work for the changelog not the release.

Reading this it seems there is not way to customize the release body is that right?
https://github.com/github-tools/github-release-notes/issues/139
