### ISSUE TITLE
Release note gets all issues

### ISSUE THREAD

**Issue by tetsuya28** [github-tools/github-release-notes#319]
With `datasources=issues` and the following GItHub Actions workflow, a Release Note has all issues with no error.
Then, run the workflow again, the Release Note gets expected issues, that have closed between the last tag and the latest tag.

```yaml
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  note:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3.8.0

      - name: Install gren
        run: |
          npm install github-release-notes -g

      - name: Create a release
        env:
          GREN_GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          gren release \
            --override \
            --tags=${{ github.ref_name }}
```

`.grenrc.yaml` is here.
```yaml
---
  dataSource: "issues"
  groupBy:
    "✨ Enhancement":
      - "enhancement"
    "🐛 Bug":
      - "bug"
  changelogFilename: "CHANGELOG.md"
  template:
    label: ""
  limit: 99
```
